name: Test macOS (Power testing lab)

on:
  workflow_dispatch:
  
  # schedule:
  #   - cron: '*/5 * * * *'
    
permissions:
  contents: read

jobs:
  test-macOS:
    strategy:
      fail-fast: false
      matrix:
        os: [ase]
        jobs: [1, 2, 3]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Environment Information
        run: system_profiler SPSoftwareDataType SPHardwareDataType && sysctl -a | grep machdep.cpu
      - name: Benchmark
        id: benchmark
        run: sh benchmark.sh
