name: Test macOS 13 public (6 core arm64 v3)

on:
  workflow_dispatch:
  
  # schedule:
  #   - cron: '*/5 * * * *'
    
permissions:
  contents: read

jobs:
  test-macOS:
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-13-xlarge"]
        jobs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Environment Information
        run: system_profiler SPSoftwareDataType SPHardwareDataType && sysctl -a | grep machdep.cpu
      - name: Benchmark
        id: benchmark
        run: sh benchmark.sh
